# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ⌂
url:                 http://andrei.oghina.com
paginate:            5
baseurl:             ""
excerpt_separator:   "<!--more-->"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andrei Oghina
  url:               http://andrei.oghina.com
  email:             andrei@oghina.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/aoghina/aoghina.github.io

pages_list:
  About: '/about'
  LinkedIn: 'https://www.linkedin.com/in/andreioghina'
  Facebook: 'https://www.facebook.com/andrei.oghina'
  TasteKid: 'http://www.tastekid.com/andrei'

#  Feed: '/atom.xml'
